### ISSUE TITLE
Could not click using ocrClickOnText() on a desktop browser version

### ISSUE THREAD

**Issue by gromanas** [wswebcreation/wdio-ocr-service#9]
**Environment:**
 - Node.js version: 14.18.1
 - Platform name and version: Chrome
 - WebdriverIO version: 7.16.4
 - wdio-ocr-service version: 1.1.0

**Config of WebdriverIO + wdio-ocr-service**
```  
 services: ['image-comparison', {
            baselineFolder: join(process.cwd(), './test/imageComparisonBaseline/'),
            formatImageName: '{tag}-{width}x{height}',
            screenshotPath: join(process.cwd(), '.tmp/'),
            savePerInstance: true,
            autoSaveBaseline: true,
            hideScrollBars: true,
            scaleImagesToSameSize: true,
        }], [ 'ocr', {
                
                ocrImagesPath: 'ocr-images/',
            },
        ]
    ],
```

**Description**
I have tried to use this service on a webapp. I have tried to use `ocrGetText()` with great success and then I was trying to use `ocrClickOnText()`. The issue that occurred was that I was constantly getting an exception for invalid argument and that the `x` must be an integer.  

**To Reproduce**
I have tried to use `ocrClickOnText()` without any option and I have tried also using `iosRectangles` and `androidRectangles` (I just use this even I tried on a desktop Chrome browser). e.g 
```
 await browser.ocrClickOnText(
            'PLAY NOW',
            {
                iOSRectangles: {
                    top: 700,
                    left: 650,
                    right: 0,
                    bottom: 0,
                },
            },
        );
```

**Expected behavior**
The function should perform the click on the text on the screen.

**Log**
```
invalid argument
from invalid argument: 'x' must be an int
```

**Additional context**
I know that this library is meant to be used on mobile, although I found it very interesting using it for a webapp on a desktop version of a browser. 

I did a first debug on `determineClickPoint()` and I found that the calculation of the `x` and `y` was actually a float number. e.g. `element position  x=1249.7098377812663 y=828.4536891679749`. In `performActions()` method the `x` and `y` should be an integer. 

If you decide that this should be fixed then I can give it a try...

**Comment by wswebcreation** [comment]
Hi @gromanas 

Thanks for the issue and debugging this. Also great that this works for Desktop. 
I have two suggestions:
- we need a fix for the int, can you create a PR for this
- based on what you found this module can also be used for desktop. Can you file a ticket that would be a feature request for this which should update the docs, check on cross browser and so on?

Thanks for your contribution so far!
